### PR TITLE
[scanner] fix: restore main build by typing settings section keys

### LINKED ISSUE #21926: 🐛 Build broken after merging PR #21902
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21902.

| Detail | Value |
|--------|-------|
| **PR** | [#21902 — 🌱 Split oversized auth, onboarding, settings, and clusters components](https://github.com/kubestellar/console/pull/21902) |
| **Author** | @clubanderson |
| **Merge commit** | `40d078cb6a16798a2362ee7035e698d95f0824bd` |
| **Detected at** | 2026-07-29 21:08 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/settings/Settings.parts.tsx(226,10): error TS2345: Argument of type '[string]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '[string]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type 'string' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[]'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/auth/LocalLoginForm.parts.tsx
web/src/components/auth/LocalLoginForm.tsx
web/src/components/auth/useLocalLogin.ts
web/src/components/clusters/AddClusterDialog.tsx
web/src/components/clusters/Clusters.parts.tsx
web/src/components/clusters/ResourceDetailModals.tsx
web/src/components/clusters/resource-modals/CPUDetailModal.tsx
web/src/components/clusters/resource-modals/GPUDetailModal.tsx
web/src/components/clusters/resource-modals/MemoryDetailModal.tsx
web/src/components/clusters/resource-modals/StorageDetailModal.tsx
web/src/components/clusters/resource-modals/shared.tsx
web/src/components/clusters/useAddClusterForm.ts
web/src/components/clusters/useClustersView.ts
web/src/components/layout/ProfileCard.parts.tsx
web/src/components/onboarding/Tour.parts.tsx
web/src/components/onboarding/Tour.tsx
web/src/components/settings/Settings.parts.tsx
web/src/components/settings/Settings.tsx
web/src/components/settings/UpdateSettingsForm.fields.tsx
web/src/components/settings/UpdateSettingsForm.tsx
web/src/components/settings/sections/GitHubTokenSection.tsx
web/src/components/settings/sections/LocalClustersSection.parts.tsx
web/src/components/settings/sections/LocalClustersSection.tsx
web/src/components/settings/sections/useGitHubToken.ts
web/src/components/settings/sections/useLocalClusters.ts
web/src/components/settings/useSettingsTabs.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30490796910) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21927: 🐛 Build broken after merging PR #21890
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21890.

| Detail | Value |
|--------|-------|
| **PR** | [#21890 — 🌱 Split CRDDrillDown.tsx (695 → 236 lines)](https://github.com/kubestellar/console/pull/21890) |
| **Author** | @clubanderson |
| **Merge commit** | `52b244aef27f7e9689947ec239d1c1e5b03454e6` |
| **Detected at** | 2026-07-29 21:08 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/settings/Settings.parts.tsx(226,10): error TS2345: Argument of type '[string]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '[string]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type 'string' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[]'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/clusters/Clusters.parts.tsx
web/src/components/clusters/useClustersView.ts
web/src/components/drilldown/views/CRDDrillDown.parts.tsx
web/src/components/drilldown/views/CRDDrillDown.tsx
web/src/components/drilldown/views/CRDDrillDown.types.ts
web/src/components/drilldown/views/useCRDDrillDown.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30490884405) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21928: 🐛 Build broken after merging PR #21892
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21892.

| Detail | Value |
|--------|-------|
| **PR** | [#21892 — [scanner] fix: close auto-qa quality findings batch](https://github.com/kubestellar/console/pull/21892) |
| **Author** | @clubanderson |
| **Merge commit** | `e0f4e26cb10ef6c4457793aaea6856b9ae725f77` |
| **Detected at** | 2026-07-29 21:09 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/settings/Settings.parts.tsx(226,10): error TS2345: Argument of type '[string]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '[string]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type 'string' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[]'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/ui/AlertBadge.tsx
web/src/components/ui/AlertBadge.utils.ts
web/src/components/ui/__tests__/AlertBadge.utils.test.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30490852232) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21929: 🐛 Build broken after merging PR #21859
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21859.

| Detail | Value |
|--------|-------|
| **PR** | [#21859 — 🐛 fix: normalize sign-of-zero in toRFC3339StartDate UTC test assertion](https://github.com/kubestellar/console/pull/21859) |
| **Author** | @clubanderson |
| **Merge commit** | `a432e52928d74e9cde98a09440283382da11de60` |
| **Detected at** | 2026-07-29 21:09 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/settings/Settings.parts.tsx(226,10): error TS2345: Argument of type '[string]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '[string]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type 'string' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4822 more ... | ("layout.watchdogStageWatchdog" | ... 4825 more ... | "whiteLabel.copyCommands")[]'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```

```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30490904061) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21926
Fixes #21927
Fixes #21928
Fixes #21929

## Summary
- narrow `SectionGroupHeader` `labelKey` from `string` to the `SETTINGS_NAV` group-key union
- resolve i18next typed key mismatch (`TS2345`) in `Settings.parts.tsx` that broke main `Build and Deploy KC`

### CODE REVIEW

**Comment by clubanderson** [comment]
Closing as superseded/stale.

`Settings.parts.tsx` now has the typed group-key fix on `main`, and this branch remains in merge-conflict state against current base. Keeping this PR open no longer provides unique value and blocks queue throughput.
