### PR TITLE
🐛 Fix TS compiler crash from invalid i18n keys with object args

### LINKED ISSUE #21967: 🐛 Build broken after merging PR #21959
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21959.

| Detail | Value |
|--------|-------|
| **PR** | [#21959 — [scanner] fix: split NetworkGlobe and address auto-qa quality issues](https://github.com/kubestellar/console/pull/21959) |
| **Author** | @clubanderson |
| **Merge commit** | `9c7aa6936b8cb3e43f1be121b66d336e18905447` |
| **Detected at** | 2026-07-30 05:24 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/drilldown/views/helm-release-drilldown/HelmOverviewPanel.tsx(121,20): error TS2345: Argument of type '["common.moreItems", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4834 more ... | ("layout.watchdogStageWatchdog" | ... 4837 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common.moreItems", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/animations/globe/NetworkGlobe.geometry.ts
web/src/components/animations/globe/NetworkGlobe.tsx
web/src/components/dashboard/customDashboard/DashboardEmptyState.tsx
web/src/components/drilldown/views/helm-release-drilldown/HelmOverviewPanel.tsx
web/src/components/drilldown/views/multi-cluster-summary-drilldown/ClusterSummaryCard.tsx
web/src/locales/en/common.json
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30516246378) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21976: 🐛 Build broken after merging PR #21960
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21960.

| Detail | Value |
|--------|-------|
| **PR** | [#21960 — 🌱 refactor: split oversized drilldown components](https://github.com/kubestellar/console/pull/21960) |
| **Author** | @clubanderson |
| **Merge commit** | `960a6fc5aa1ea9dfe6c9a18d55f5d1ac44774bf7` |
| **Detected at** | 2026-07-30 05:46 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:123693
      throw e;
      ^

Error: Debug Failure. No error for last overload signature
    at resolveCall (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:76665:19)
    at resolveCallExpression (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77047:12)
    at resolveSignature (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77475:16)
    at getResolvedSignature (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77502:20)
    at checkCallExpression (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77610:23)
    at checkExpressionWorker (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:81068:16)
    at checkExpression (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:80966:32)
    at checkExpressionCached (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:80590:28)
    at checkVariableLikeDeclaration (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:83508:35)
    at checkVariableDeclaration (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:83604:5)

Node.js v22.23.1
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/drilldown/views/EventsDrillDown.parts.tsx
web/src/components/drilldown/views/EventsDrillDown.tsx
web/src/components/drilldown/views/NamespaceDrillDown.parts.tsx
web/src/components/drilldown/views/NamespaceDrillDown.tsx
web/src/components/drilldown/views/PVCDrillDown.parts.tsx
web/src/components/drilldown/views/PVCDrillDown.tsx
web/src/components/drilldown/views/PolicyDrillDown.parts.tsx
web/src/components/drilldown/views/PolicyDrillDown.tsx
web/src/components/drilldown/views/ReplicaSetDrillDown.parts.tsx
web/src/components/drilldown/views/ReplicaSetDrillDown.tsx
web/src/components/drilldown/views/useEventsDrillDown.ts
web/src/components/drilldown/views/useNamespaceDrillDown.ts
web/src/components/drilldown/views/usePVCDrillDown.ts
web/src/components/drilldown/views/usePolicyDrillDown.ts
web/src/components/drilldown/views/useReplicaSetDrillDown.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30517275575) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21967
Fixes #21976

## Root cause

`main` is broken: `npm run build` (`tsc -b`) crashes with:

```
Error: Debug Failure. No error for last overload signature
    at resolveCall (.../_tsc.js:76665:19)
    ...
```

This is a known upstream TypeScript compiler bug ([microsoft/TypeScript#63195](https://github.com/microsoft/TypeScript/issues/63195)): when react-i18next's `TFunction` is auto-typed from a very large `typeof resources` object (this repo's `en/common.json` alone contains ~4800+ leaf keys), calling `t()` with a **key that isn't part of the typed union** *and* an **object-typed second argument** (interpolation `options`) forces TS to resolve an enormous overload set. Instead of emitting a normal type error, the compiler hits an internal assertion and aborts the whole build.

I bisected the exact expressions that trip this:

- `HelmOverviewPanel.tsx`: `t('common.moreItems', { count })` — `common.moreItems` does not exist in `common.json` (this was the TS2345 reported in #21967; PR #21973 only addressed this file, but a second, worse crash from #21960 still blocks `main`).
- `EventsDrillDown.parts.tsx` (introduced by #21960's drilldown split): `t('drilldown.events.showingRange', { from, to, total, defaultValue })` and `t('drilldown.events.pageOf', { page, total, defaultValue })` — neither `drilldown.events.showingRange` nor `drilldown.events.pageOf` exist in `common.json`.

Note: the repo has many other calls like `t(someInvalidKey, 'Some default string')` (string as 2nd arg). Those do **not** trigger the crash — this pattern predates #21959/#21960 and is unaffected by this PR, so it was left untouched to keep the change minimal.

## Fix

Point the offending `t()` calls at translation keys that already exist in `web/src/locales/en/common.json`, and add the one genuinely missing key (`pagination.pageOf`):

- `HelmOverviewPanel.tsx`: `common.moreItems` → `labels.moreItems` (already `"+{{count}} more"`).
- `EventsDrillDown.parts.tsx`:
  - `drilldown.events.showingRange` → `pagination.showing` (already `"Showing {{start}}-{{end}} of {{total}}"`; renamed the `from`/`to` interpolation vars to `start`/`end` to match).
  - `common.previousPage` / `common.nextPage` → `pagination.previousPage` / `pagination.nextPage` (already exist with identical English text).
  - `drilldown.events.pageOf` → new `pagination.pageOf` key (`"Page {{page}} of {{total}}"`), added to `en/common.json` since no equivalent existed.

No behavioral change: all replacement keys render the same English text as the previous inline `defaultValue` fallbacks.

## Superseding note

This PR supersedes/completes the intent of #21973, which only patched the `HelmOverviewPanel` TS2345 symptom and did not touch the `EventsDrillDown.parts.tsx` crash from #21960 that is still blocking `main`. #21973 can likely be closed in favor of this PR once merged.

## Files changed

- `web/src/components/drilldown/views/EventsDrillDown.parts.tsx`
- `web/src/components/drilldown/views/helm-release-drilldown/HelmOverviewPanel.tsx`
- `web/src/locales/en/common.json`

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>

### CODE REVIEW

**Comment by clubanderson** [comment]
FYI: this fixes the two invalid i18n keys that trip the `tsc -b` crash on `main` today (confirmed via this PR's own CI log, `Build Frontend` job — the crash is gone there), but I found ~60+ *other* missing i18n keys elsewhere in the codebase using the same crash-triggering pattern (`t(key, { ...interpolation, defaultValue })` with a key not present in `common.json`/`cards.json`) that would reintroduce this exact failure the next time one of them is touched. So this fix isn't scale-proof against future recurrences.

Opened #22015 which root-causes the bug by removing the `typeof`-derived resources typing entirely, so it can't recur regardless of which/how many keys are missing. Verified green on `Build Frontend` / multi-arch `build` / `fullstack-smoke`. Linking here for visibility — not asking you to close this.

**Comment by clubanderson** [comment]
Pushed a fixup commit (`936dc1df09`) merging latest `main` into this branch. `main` already merged #21993-equivalent i18n key fixes (`pagination.showing`/`pagination.pageOf`/etc. in `EventsDrillDown.parts.tsx` and `common.json`) plus #22014's removal of the `CustomTypeOptions.resources` typing in `i18n.ts`. Resolved conflicts in `EventsDrillDown.parts.tsx` and `i18n.ts` by keeping `main`'s already-verified versions (main's copy additionally kept the `defaultValue` string fallbacks on `previousPage`/`nextPage`). This should clear the `Build Frontend`/`build-gate` failures.
