### PR TITLE
🐛 fix: add missing Loader2 import in QuantumControlPanel

### LINKED ISSUE #18221: 🐛 Frontend build broken: missing Loader2 import in QuantumControlPanel.tsx (regression from PR #18200)
## What broke

Frontend build fails on `main` (`6c4b0255f19d`) with:

```
src/components/cards/quantum/QuantumControlPanel.tsx:695:54 -
  error TS2304: Cannot find name 'Loader2'.

695   {(control.executing || isExecuting) ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
                                              ~~~~~~~

Found 1 error.
```

## Root cause

PR #18200 ([scanner] add loading states to async action buttons) added a `<Loader2 />` spinner at `web/src/components/cards/quantum/QuantumControlPanel.tsx:695` but did not include `Loader2` in the existing `lucide-react` destructured import on line 2.

Existing import (line 2):
```ts
import { AlertCircle, Play, Zap, Key, Check, Trash2, ShieldCheck, RefreshCw } from 'lucide-react'
```

Other files modified by PR #18200 may have the same pattern — worth a sweep.

## Reproduction

```bash
git checkout 6c4b0255f
./startup-oauth.sh
# Frontend build fails with TS2304
```

## Fix

PR #18220 — adds `Loader2` to the existing `lucide-react` import. One-line.

cc @kubestellar-hive — please scan the rest of PR #18200's changed files (`grep -l 'Loader2' web/src/components/cards/`) for the same missing-import pattern.

### PR DESCRIPTION
**Pull request by KPRoche**
Fixes #18221

## Summary

PR #18200 ([scanner] add loading states to async action buttons) introduced `<Loader2 />` JSX in `QuantumControlPanel.tsx:695` but did not include `Loader2` in the existing `lucide-react` import on line 2, breaking the frontend build:

```
src/components/cards/quantum/QuantumControlPanel.tsx:695:54 -
  error TS2304: Cannot find name 'Loader2'.

695   {(control.executing || isExecuting) ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
```

## Fix

One-line: add `Loader2` to the existing destructured `lucide-react` import.

```diff
-import { AlertCircle, Play, Zap, Key, Check, Trash2, ShieldCheck, RefreshCw } from 'lucide-react'
+import { AlertCircle, Play, Zap, Key, Check, Trash2, ShieldCheck, RefreshCw, Loader2 } from 'lucide-react'
```

## Test plan

- [x] Reproduces TS2304 without the import; clean with it
- [x] Frontend `tsc -b && vite build` passes locally
- [ ] CI passes

### CODE REVIEW

**Comment by KPRoche** [comment]
Closing in favor of #18215, which was filed 49 minutes earlier (22:47Z vs 23:36Z) and is strictly broader in scope.

This PR added `Loader2` to the import only. #18215 also wires the `isExecuting` state and updates the Execute button to actually render the spinner during execution — which is what PR #18200 was supposed to do. Copilot's automated review on this PR flagged the same concern (unused import).

Apologies for the redundancy — I missed #18211 / #18215 when triaging the failed build locally. Sorry @kubestellar-hive for the duplicate work.

Companion issue #18221 will be closed in favor of #18211.
