### PR TITLE
🐛 fix: ensure capabilities is defined before accessing add property

### LINKED ISSUE #21850: 🐛 Build broken after merging PR #21839
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21839.

| Detail | Value |
|--------|-------|
| **PR** | [#21839 — 🌱 Split rbac/CanIChecker.tsx (615 → 302 lines)](https://github.com/kubestellar/console/pull/21839) |
| **Author** | @clubanderson |
| **Merge commit** | `22d98d91fddd14737edc0b287b441003b41a19a3` |
| **Detected at** | 2026-07-29 08:22 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/hooks/useCachedCoreWorkloads.ts(148,17): error TS18048: 'sc.capabilities.add.length' is possibly 'undefined'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/rbac/CanIChecker.constants.ts
web/src/components/rbac/CanIChecker.parts.tsx
web/src/components/rbac/CanIChecker.state.ts
web/src/components/rbac/CanIChecker.tsx
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30434867119) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21850

## Root Cause

TypeScript error in useCachedCoreWorkloads.ts when checking if capabilities.add has items. The optional chaining wasn't sufficient for type narrowing; an explicit null check is required.

## Fix

Add explicit `sc.capabilities` check before accessing the `add` property to satisfy TypeScript's type narrowing requirements.

Changes:
- web/src/hooks/useCachedCoreWorkloads.ts: Add null check before accessing capabilities.add

Signed-off-by: Scanner <scanner@kubestellar.io>
Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>

### CODE REVIEW

**Comment by clubanderson** [comment]
Superseded by #21838, which has been updated to include the same `useCachedCoreWorkloads.ts` capabilities-guard fix on branch `scanner/fix-21545`. Verified locally that `npx tsc -b --force` succeeds (exit 0) with all changes from #21838 combined. Closing this PR as a duplicate to avoid overlapping merges; please review/merge #21838 instead.
