### PR TITLE
[scanner] fix: resolve TypeScript build errors on main

### LINKED ISSUE #21764: 🐛 Build broken after merging PR #21754
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21754.

| Detail | Value |
|--------|-------|
| **PR** | [#21754 — [scanner] fix: split CardWrapper and ConsoleOfflineDetectionCard components](https://github.com/kubestellar/console/pull/21754) |
| **Author** | @clubanderson |
| **Merge commit** | `c1716e9b435eef6d07d19c06d6009fad9a4ee81f` |
| **Detected at** | 2026-07-29 02:02 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(39,50): error TS6133: 'filteredCriticalPredicted' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/cards/CardWrapper.constants.ts
web/src/components/cards/CardWrapper.tsx
web/src/components/cards/CardWrapper.types.ts
web/src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx
web/src/components/cards/console-missions/useOfflineDetection.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30415456473) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21765: Workflow failure: Build and Deploy KC
## Workflow Failure

The **Build and Deploy KC** workflow failed.

| Detail | Value |
|--------|-------|
| **Workflow** | `Build and Deploy KC` |
| **Run** | [#30415456279](https://github.com/kubestellar/console/actions/runs/30415456279) |
| **File** | `.github/workflows/build-deploy.yml` |
| **Time** | 2026-07-29 02:03 UTC |
| **Failed jobs** | `build (linux/arm64, ubuntu-24.04-arm, arm64), build (linux/amd64, ubuntu-24.04, amd64)` |

### Next Steps
1. Check the [failed run](https://github.com/kubestellar/console/actions/runs/30415456279) for error details
2. Fix the underlying issue
3. **Do not close** this issue until the workflow passes on `main`

---
*This issue was automatically created by the workflow failure monitor.*

### LINKED ISSUE #21766: 🐛 Build broken after merging PR #21759
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21759.

| Detail | Value |
|--------|-------|
| **PR** | [#21759 — [scanner] fix: split dialog and section components (SaveResolution, AlertRuleEditor, Clusters)](https://github.com/kubestellar/console/pull/21759) |
| **Author** | @clubanderson |
| **Merge commit** | `ade78b3611eca268bd1117aeda8a435e8e83aba4` |
| **Detected at** | 2026-07-29 02:05 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/cards/CardHeader.tsx(81,45): error TS2345: Argument of type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly title: string; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ title: string; }' is not assignable to type 'string'.
src/components/cards/CardWrapper.tsx(665,13): error TS2589: Type instantiation is excessively deep and possibly infinite.
src/components/cards/CardWrapper.tsx(671,15): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(681,58): error TS2322: Type 'string' is not assignable to type 'void | Promise<void>'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(710,9): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(59,15): error TS2345: Argument of type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(60,15): error TS2345: Argument of type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.allHealthy"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(83,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.gpuIssues"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(125,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.predicted"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.predicted"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.predicted"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/settings/sections/LocalClustersSection.tsx(332,13): error TS2322: Type 'LocalClusterTool[]' is not assignable to type 'ToolInfo[]'.
  Type 'LocalClusterTool' is not assignable to type 'ToolInfo'.
    Types of property 'version' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/alerts/AlertPreviewPanel.tsx
web/src/components/alerts/AlertRuleEditor.tsx
web/src/components/alerts/ConditionBuilder.tsx
web/src/components/alerts/NotificationChannelSelector.tsx
web/src/components/cards/CardErrorBoundary.tsx
web/src/components/cards/CardFooter.tsx
web/src/components/cards/CardHeader.tsx
web/src/components/cards/CardWrapper.tsx
web/src/components/cards/ResizeHandle.tsx
web/src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx
web/src/components/cards/console-missions/OfflineStatusDisplay.tsx
web/src/components/cards/console-missions/useOfflineDetection.ts
web/src/components/missions/ConflictList.tsx
web/src/components/missions/ResolutionForm.tsx
web/src/components/missions/SaveResolutionDialog.tsx
web/src/components/settings/sections/AddClusterForm.tsx
web/src/components/settings/sections/ClusterRow.tsx
web/src/components/settings/sections/ImportWizard.tsx
web/src/components/settings/sections/LocalClustersSection.tsx
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30415584314) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21773: 🐛 Build broken after merging PR #21757
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21757.

| Detail | Value |
|--------|-------|
| **PR** | [#21757 — [scanner] fix: split DashboardState.ts and add coverage for extracted modules](https://github.com/kubestellar/console/pull/21757) |
| **Author** | @clubanderson |
| **Merge commit** | `b3796b5ffbfb4caf9ae46bb9d084155252e87452` |
| **Detected at** | 2026-07-29 02:07 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/cards/CardHeader.tsx(81,45): error TS2345: Argument of type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly title: string; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ title: string; }' is not assignable to type 'string'.
src/components/cards/CardWrapper.tsx(665,13): error TS2589: Type instantiation is excessively deep and possibly infinite.
src/components/cards/CardWrapper.tsx(671,15): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(681,58): error TS2322: Type 'string' is not assignable to type 'void | Promise<void>'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(710,9): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(59,15): error TS2345: Argument of type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(60,15): error TS2345: Argument of type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.allHealthy"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(83,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.gpuIssues"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(125,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.predicted"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.predicted"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.predicted"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/settings/sections/LocalClustersSection.tsx(332,13): error TS2322: Type 'LocalClusterTool[]' is not assignable to type 'ToolInfo[]'.
  Type 'LocalClusterTool' is not assignable to type 'ToolInfo'.
    Types of property 'version' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/dashboard/DashboardState.ts
web/src/components/dashboard/dashboardState.sensors.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30415662581) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21774: 🐛 Build broken after merging PR #21755
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21755.

| Detail | Value |
|--------|-------|
| **PR** | [#21755 — [scanner] fix: ErrorBoundary wrapping and error state exposure in hooks](https://github.com/kubestellar/console/pull/21755) |
| **Author** | @clubanderson |
| **Merge commit** | `60fa01f646f4a538c4e6fe29c74cc77d767b450e` |
| **Detected at** | 2026-07-29 02:07 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/cards/CardHeader.tsx(81,45): error TS2345: Argument of type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly title: string; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ title: string; }' is not assignable to type 'string'.
src/components/cards/CardWrapper.tsx(665,13): error TS2589: Type instantiation is excessively deep and possibly infinite.
src/components/cards/CardWrapper.tsx(671,15): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(681,58): error TS2322: Type 'string' is not assignable to type 'void | Promise<void>'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(710,9): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(59,15): error TS2345: Argument of type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(60,15): error TS2345: Argument of type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.allHealthy"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(83,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.gpuIssues"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(125,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.predicted"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.predicted"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.predicted"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/settings/sections/LocalClustersSection.tsx(332,13): error TS2322: Type 'LocalClusterTool[]' is not assignable to type 'ToolInfo[]'.
  Type 'LocalClusterTool' is not assignable to type 'ToolInfo'.
    Types of property 'version' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
src/hooks/useAlerts.ts(39,10): error TS6133: 'saveToStorage' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/namespaces/NamespaceManager.tsx
web/src/hooks/useAlerts.ts
web/src/hooks/useDashboardCards.ts
web/src/hooks/useLocalClusterTools.ts
web/src/hooks/usePersistence.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30415679896) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21764, Fixes #21765, Fixes #21766, Fixes #21773, Fixes #21774

## TypeScript Build Error Fixes

Resolves 11 TypeScript errors introduced by component-split PRs #21754–#21759.

### Changes

**`web/src/components/cards/CardHeader.tsx`**
- Relax `t` prop type from `TFunction` (i18next branded) to `(key: string, options?: Record<string, unknown>) => string`
- Fixes TS2322/TS2589 — brand mismatch when `CardWrapper` passes `TFunction<['cards','common']>`

**`web/src/components/cards/console-missions/OfflineStatusDisplay.tsx`**
- Remove `t: TFunction` prop; call `useTranslation('cards')` and `useTranslation('common')` internally
- Replace namespace-prefixed keys (`common:...`, `cards:...`) with direct keys on the correct hook
- Fixes TS2345 at lines 59, 60, 83, 125

**`web/src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx`**
- Remove `t={t}` prop from `<OfflineStatusDisplay>` (no longer needed)
- Wrap `startMission(analysisMissionConfig)` in block body `{ }` to discard `string` return value
- Fixes TS2322 at lines 681 and 710

**`web/src/components/settings/sections/AddClusterForm.tsx`**
- Widen `ToolInfo.version` from `string` to `string | undefined` to match `LocalClusterTool`
- Fixes TS2322 in `LocalClustersSection.tsx:332`

**`web/src/hooks/useAlerts.ts`**
- Remove unused `saveToStorage` helper function
- Fixes TS6133

### CODE REVIEW

**Comment by clubanderson** [comment]
Scanner update attempt hit base/head merge conflicts after latest master changes. Skipping auto-resolution this cycle because conflicts span substantive TypeScript files; this PR needs a manual conflict resolution rebase before merge.

**Comment by clubanderson** [comment]
This TypeScript build fix is already covered on current `main` (the same CardHeader / OfflineStatusDisplay / AddClusterForm / useAlerts errors were resolved in the later mainline fix at commit `288b64d2`). Keeping this branch open would duplicate changes already merged upstream.
