### PR TITLE
[scanner] fix: resolve Lucide icon type incompatibilities

### LINKED ISSUE #21514: 🐛 Build broken after merging PR #21513
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21513.

| Detail | Value |
|--------|-------|
| **PR** | [#21513 — ✨ fix: resolve refresh icon spin animation inconsistencies](https://github.com/kubestellar/console/pull/21513) |
| **Author** | @clubanderson |
| **Merge commit** | `8fd7b11e6f13e7e4e915e7940154839e18a87404` |
| **Detected at** | 2026-07-25 15:02 UTC |

### Frontend Build Failure
```
src/components/layout/navbar/SearchResultsPanel.tsx(12,33): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(12,51): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(13,33): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(13,51): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(14,37): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(14,55): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(15,39): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(15,57): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(16,25): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(16,43): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(17,33): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(17,51): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(18,36): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(18,54): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(19,44): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(19,62): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(20,35): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(20,53): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
src/components/layout/navbar/SearchResultsPanel.tsx(21,27): error TS2741: Property '$$typeof' is missing in type '(props: Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>) => Element' but required in type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>'.
src/components/layout/navbar/SearchResultsPanel.tsx(21,45): error TS2322: Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Type '{ children: string; string?: string | number | undefined; key?: Key | null | undefined; slot?: string | undefined; style?: CSSProperties | undefined; method?: string | undefined; ... 483 more ...; ref?: Ref<...> | undefined; }' is not assignable to type 'ClassAttributes<HTMLDivElement>'.
    Types of property 'ref' are incompatible.
      Type 'Ref<SVGSVGElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
        Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
          Type '(instance: SVGSVGElement | null) => void | (() => VoidOrUndefinedOnly)' is not assignable to type '(instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly)'.
            Types of parameters 'instance' and 'instance' are incompatible.
              Type 'HTMLDivElement | null' is not assignable to type 'SVGSVGElement | null'.
                Type 'HTMLDivElement' is missing the following properties from type 'SVGSVGElement': currentScale, currentTranslate, height, width, and 55 more.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
COMPONENT_SPLIT_SUMMARY.md
web/src/components/cards/GPUInventoryHistory.tsx
web/src/components/cards/NamespaceQuotas.tsx
web/src/components/cards/QualityDashboard.tsx
web/src/components/cards/cloud_custodian_status/index.tsx
web/src/components/cards/containerd_status/index.tsx
web/src/components/cards/spire_status/index.tsx
web/src/components/layout/navbar/AgentStatusIndicator.parts.tsx
web/src/components/layout/navbar/SearchDropdown.tsx
web/src/components/layout/navbar/SearchResultsPanel.tsx
web/src/components/missions/AIUtils.parts.tsx
web/src/components/missions/ValidationAndHandlers.parts.tsx
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30162604373) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21514, Fixes #21516

Resolves TypeScript build errors related to Lucide icon type incompatibilities in SearchResultsPanel and KagentiLifecycleManager.

**Changes:**
- SearchResultsPanel.tsx: Changed `icon: typeof Bot` to `icon: React.ComponentType<{ className?: string }>`
- KagentiLifecycleManager.tsx: Changed `icon: typeof Bot` to `icon: React.ComponentType<{ className?: string }>`

This matches the established pattern used throughout the codebase for accepting icon components as props.

### CODE REVIEW

**Comment by clubanderson** [comment]
## [quality] Duplicate PR

This PR makes the **identical 2-line change** as **#21517** (both modify `SearchResultsPanel.tsx` and `KagentiLifecycleManager.tsx` from `icon: typeof Bot` → `icon: React.ComponentType<{ className?: string }>`).

Diff — PR #21517:
- `web/src/components/cards/kagenti/KagentiLifecycleManager.tsx`: 1 line
- `web/src/components/layout/navbar/SearchResultsPanel.tsx`: 1 line

Diff — PR #21523 (this PR):
- `web/src/components/cards/kagenti/KagentiLifecycleManager.tsx`: 1 line
- `web/src/components/layout/navbar/SearchResultsPanel.tsx`: 1 line

Same files, same replacement, same base SHA (`8fd7b11e`). Only difference: this PR references `Fixes #21514, Fixes #21516`, while #21517 references only `Fixes #21516`.

**Recommendation:** close one of the two. If both target issues (#21514, #21516) truly need this same one-line change, close **#21517** and keep this one; otherwise close this one and let #21517 close #21516. Merging both would just have git detect one as a no-op.

A test for icon-prop typing is not warranted — this is a type-signature fix that the tsc build already validates.

---
*Filed by quality agent (ACMM L4/L6 — full mode)*

**Comment by clubanderson** [comment]
## [quality] Superseded by #21552 for `SearchResultsPanel.tsx`

Reiterating the note from my earlier duplicate-PR comment, now with more context:

**PR #21552 supersedes this PR (and the identical #21517) for the `SearchResultsPanel.tsx` change** and root-causes the CI failure. The bug in `SearchResultsPanel.tsx` was not the `icon: typeof Bot` type — it was that #21513's extraction had silently replaced the lucide `CATEGORY_CONFIG` components with emoji-arrow-functions. This PR's approach of widening the prop type to `React.ComponentType<{ className?: string }>` makes the emoji version typecheck but ships the visual regression to users (📊/🎴/📈 instead of proper lucide icons in the global-search dropdown).

#21552 restores the lucide icons byte-for-byte and adds a Playwright visual regression test that guards this class of extraction regression.

**Recommendation:** close this PR (and #21517) once #21552 lands. The `KagentiLifecycleManager.tsx` change may stand independently — if that file's callers genuinely need `React.ComponentType<{ className?: string }>` (not just `typeof Bot`), file it as a small standalone follow-up.

---
*Filed by quality agent (ACMM L4/L6 — full mode)*
