### PR TITLE
🐛 fix: resolve remaining TypeScript build errors

### LINKED ISSUE #21833: 🐛 Build broken after merging PR #21821
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21821.

| Detail | Value |
|--------|-------|
| **PR** | [#21821 — chore: auto-qa tuning config update (CNCF intelligence) 2026-07-29](https://github.com/kubestellar/console/pull/21821) |
| **Author** | @github-actions[bot] |
| **Merge commit** | `994368554cc376246ee3aaed05bd4f2862a879e4` |
| **Detected at** | 2026-07-29 06:08 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/cards/CardHeader.tsx(81,45): error TS2345: Argument of type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly title: string; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ title: string; }' is not assignable to type 'string'.
src/components/cards/CardWrapper.tsx(665,13): error TS2589: Type instantiation is excessively deep and possibly infinite.
src/components/cards/CardWrapper.tsx(671,15): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(681,58): error TS2322: Type 'string' is not assignable to type 'void | Promise<void>'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(710,9): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(59,15): error TS2345: Argument of type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(60,15): error TS2345: Argument of type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.allHealthy"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(83,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.gpuIssues"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(125,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.predicted"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.predicted"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.predicted"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/settings/sections/LocalClustersSection.tsx(332,13): error TS2322: Type 'LocalClusterTool[]' is not assignable to type 'ToolInfo[]'.
  Type 'LocalClusterTool' is not assignable to type 'ToolInfo'.
    Types of property 'version' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
src/hooks/useAlerts.ts(39,10): error TS6133: 'saveToStorage' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
.github/auto-qa-tuning.json
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30426857986) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21834: 🐛 Build broken after merging PR #21819
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21819.

| Detail | Value |
|--------|-------|
| **PR** | [#21819 — [quality] test: 48 unit tests for BatchMonitorModal.utils](https://github.com/kubestellar/console/pull/21819) |
| **Author** | @clubanderson |
| **Merge commit** | `3e2077986777923598b4c637bd901d9794754f7c` |
| **Detected at** | 2026-07-29 06:08 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/cards/CardHeader.tsx(81,45): error TS2345: Argument of type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["messages.descriptionComingSoon", { title: string; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly title: string; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ title: string; }' is not assignable to type 'string'.
src/components/cards/CardWrapper.tsx(665,13): error TS2589: Type instantiation is excessively deep and possibly infinite.
src/components/cards/CardWrapper.tsx(671,15): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(681,58): error TS2322: Type 'string' is not assignable to type 'void | Promise<void>'.
src/components/cards/console-missions/ConsoleOfflineDetectionCard.tsx(710,9): error TS2322: Type 'TFunction<readonly ["cards", "common"], undefined>' is not assignable to type 'TFunction<"common", undefined>'.
  Types of property '$TFunctionBrand' are incompatible.
    Type '"cards"' is not assignable to type '"common"'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(59,15): error TS2345: Argument of type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common:healthCheck.issuesTooltip", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(60,15): error TS2345: Argument of type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.allHealthy"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.allHealthy"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(83,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.gpuIssues"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.gpuIssues"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/cards/console-missions/OfflineStatusDisplay.tsx(125,14): error TS2345: Argument of type '["cards:consoleOfflineDetection.predicted"]' is not assignable to parameter of type '[key: string | string[], options: TOptionsBase & $Dictionary & { defaultValue: string; }] | [key: string | string[], defaultValue: string, options?: (TOptionsBase & $Dictionary) | undefined] | [key: ...]'.
  Type '["cards:consoleOfflineDetection.predicted"]' is not assignable to type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[], options?: (TOptionsBase & ...'.
    Type at position 0 in source is not compatible with type at position 0 in target.
      Type '"cards:consoleOfflineDetection.predicted"' is not assignable to type '"layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4821 more ... | ("layout.watchdogStageWatchdog" | ... 4824 more ... | "whiteLabel.copyCommands")[]'.
src/components/settings/sections/LocalClustersSection.tsx(332,13): error TS2322: Type 'LocalClusterTool[]' is not assignable to type 'ToolInfo[]'.
  Type 'LocalClusterTool' is not assignable to type 'ToolInfo'.
    Types of property 'version' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
src/hooks/useAlerts.ts(39,10): error TS6133: 'saveToStorage' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/stellar/__tests__/BatchMonitorModal.utils.test.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30426885455) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21835: Workflow failure: Release
## Workflow Failure

The **Release** workflow failed.

| Detail | Value |
|--------|-------|
| **Workflow** | `Release` |
| **Run** | [#30426852413](https://github.com/kubestellar/console/actions/runs/30426852413) |
| **File** | `.github/workflows/release.yml` |
| **Time** | 2026-07-29 06:16 UTC |
| **Failed jobs** | `test, release` |

### Next Steps
1. Check the [failed run](https://github.com/kubestellar/console/actions/runs/30426852413) for error details
2. Fix the underlying issue
3. **Do not close** this issue until the workflow passes on `main`

---
*This issue was automatically created by the workflow failure monitor.*

### LINKED ISSUE #21848: 🐛 Build broken after merging PR #21782
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21782.

| Detail | Value |
|--------|-------|
| **PR** | [#21782 — [quality] test: 61 unit tests for EventModal.utils and GPUDetailModal.utils](https://github.com/kubestellar/console/pull/21782) |
| **Author** | @clubanderson |
| **Merge commit** | `0cb367b5150558d33835fc6554cab857e0e4599a` |
| **Detected at** | 2026-07-29 08:18 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/hooks/useCachedCoreWorkloads.ts(148,17): error TS18048: 'sc.capabilities.add.length' is possibly 'undefined'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/clusters/components/__tests__/GPUDetailModal.utils.test.ts
web/src/components/stellar/__tests__/EventModal.utils.test.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30434537244) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21849: Workflow failure: Build and Deploy KC
## Workflow Failure

The **Build and Deploy KC** workflow failed.

| Detail | Value |
|--------|-------|
| **Workflow** | `Build and Deploy KC` |
| **Run** | [#30434491804](https://github.com/kubestellar/console/actions/runs/30434491804) |
| **File** | `.github/workflows/build-deploy.yml` |
| **Time** | 2026-07-29 08:18 UTC |
| **Failed jobs** | `build (linux/arm64, ubuntu-24.04-arm, arm64), build (linux/amd64, ubuntu-24.04, amd64)` |

### Next Steps
1. Check the [failed run](https://github.com/kubestellar/console/actions/runs/30434491804) for error details
2. Fix the underlying issue
3. **Do not close** this issue until the workflow passes on `main`

---
*This issue was automatically created by the workflow failure monitor.*

### LINKED ISSUE #21850: 🐛 Build broken after merging PR #21839
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21839.

| Detail | Value |
|--------|-------|
| **PR** | [#21839 — 🌱 Split rbac/CanIChecker.tsx (615 → 302 lines)](https://github.com/kubestellar/console/pull/21839) |
| **Author** | @clubanderson |
| **Merge commit** | `22d98d91fddd14737edc0b287b441003b41a19a3` |
| **Detected at** | 2026-07-29 08:22 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/hooks/useCachedCoreWorkloads.ts(148,17): error TS18048: 'sc.capabilities.add.length' is possibly 'undefined'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/rbac/CanIChecker.constants.ts
web/src/components/rbac/CanIChecker.parts.tsx
web/src/components/rbac/CanIChecker.state.ts
web/src/components/rbac/CanIChecker.tsx
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30434867119) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21833
Fixes #21834
Fixes #21835
Fixes #21848
Fixes #21849
Fixes #21850

## Changes
- Remove `readonly` from TFunction generic parameters (DeploymentIssues.tsx, StockMarketTicker.tsx, KVCacheMonitor.types.ts)
- Fix optional version type in LocalClustersSection.tsx by adding nullish coalescing operator

These fixes resolve TypeScript compilation errors cascading from PR #21783, #21821, #21819.

### CODE REVIEW

**Comment by clubanderson** [comment]
Superseded by #21838, which has been updated to include the same fix (removing `readonly` from the affected `TFunction` props and the nullish-coalescing fix in `LocalClustersSection.tsx`) on branch `scanner/fix-21545`. Verified locally that `npx tsc -b --force` succeeds (exit 0) with all changes from #21838 combined. Closing this PR as a duplicate to avoid overlapping merges; please review/merge #21838 instead.
