### PR TITLE
[scanner] fix: restore dashboard state typing on main

### LINKED ISSUE #21675: 🐛 Build broken after merging PR #21674
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21674.

| Detail | Value |
|--------|-------|
| **PR** | [#21674 — [scanner] fix: split shared lib and dashboard state modules](https://github.com/kubestellar/console/pull/21674) |
| **Author** | @clubanderson |
| **Merge commit** | `78e0e1277566b67f8ca4c645f0b38ce39a76ab5d` |
| **Detected at** | 2026-07-28 06:34 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> tsc -b && vite build

src/components/dashboard/DashboardState.ts(303,102): error TS2345: Argument of type '{ moveCardToDashboard: (cardId: string, targetDashboardId: string) => Promise<unknown>; createDashboard: (name: string, isDefault?: boolean) => Promise<Dashboard>; ... 4 more ...; t: TFunction<...>; }' is not assignable to parameter of type 'MoveToDashboardDeps'.
  The types returned by 'moveCardToDashboard(...)' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
      Type 'unknown' is not assignable to type 'void'.
src/components/dashboard/DashboardState.ts(309,63): error TS2345: Argument of type '{ moveCardToDashboard: (cardId: string, targetDashboardId: string) => Promise<unknown>; createDashboard: (name: string, isDefault?: boolean) => Promise<Dashboard>; ... 4 more ...; t: TFunction<...>; }' is not assignable to parameter of type 'MoveToDashboardDeps'.
  The types returned by 'moveCardToDashboard(...)' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
      Type 'unknown' is not assignable to type 'void'.
src/components/dashboard/DashboardState.ts(337,64): error TS2322: Type '(event: CardEvent) => void' is not assignable to type '(event: { type: string; payload: Record<string, unknown>; }) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type '{ type: string; payload: Record<string, unknown>; }' is not assignable to type 'CardEvent'.
      Type '{ type: string; payload: Record<string, unknown>; }' is not assignable to type '{ type: "deploy:result"; payload: DeployResultPayload; }'.
        Types of property 'type' are incompatible.
          Type 'string' is not assignable to type '"deploy:result"'.
src/components/dashboard/dashboardState.actions.ts(11,42): error TS6133: 'emitCardDragged' is declared but its value is never read.
src/components/dashboard/dashboardState.actions.ts(74,3): error TS6133: 'storageKey' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/dashboard/DashboardState.ts
web/src/components/dashboard/dashboardState.actions.ts
web/src/components/dashboard/dashboardState.selectors.ts
web/src/lib/acmm/sources/acmm.criteria.ts
web/src/lib/acmm/sources/acmm.levels.ts
web/src/lib/acmm/sources/acmm.ts
web/src/lib/missions/checks/classifier.ts
web/src/lib/missions/checks/remediation.ts
web/src/lib/missions/checks/runner.ts
web/src/lib/missions/checks/tools.ts
web/src/lib/missions/checks/types.ts
web/src/lib/missions/preflightCheck.ts
web/src/lib/unified/card.types.ts
web/src/lib/unified/dashboard.types.ts
web/src/lib/unified/registry.types.ts
web/src/lib/unified/stat.types.ts
web/src/lib/unified/types.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30334877327) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21676: 🐛 Build broken after merging PR #21669
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21669.

| Detail | Value |
|--------|-------|
| **PR** | [#21669 — 🌱 [quality] test: 51 unit tests for cluster-drilldown/derivedData (Fixes #21668)](https://github.com/kubestellar/console/pull/21669) |
| **Author** | @clubanderson |
| **Merge commit** | `eb9156b1e5aaf15d14b513e65c4e0bc6b1e5dd08` |
| **Detected at** | 2026-07-28 06:35 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> tsc -b && vite build

src/components/dashboard/DashboardState.ts(303,102): error TS2345: Argument of type '{ moveCardToDashboard: (cardId: string, targetDashboardId: string) => Promise<unknown>; createDashboard: (name: string, isDefault?: boolean) => Promise<Dashboard>; ... 4 more ...; t: TFunction<...>; }' is not assignable to parameter of type 'MoveToDashboardDeps'.
  The types returned by 'moveCardToDashboard(...)' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
      Type 'unknown' is not assignable to type 'void'.
src/components/dashboard/DashboardState.ts(309,63): error TS2345: Argument of type '{ moveCardToDashboard: (cardId: string, targetDashboardId: string) => Promise<unknown>; createDashboard: (name: string, isDefault?: boolean) => Promise<Dashboard>; ... 4 more ...; t: TFunction<...>; }' is not assignable to parameter of type 'MoveToDashboardDeps'.
  The types returned by 'moveCardToDashboard(...)' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
      Type 'unknown' is not assignable to type 'void'.
src/components/dashboard/DashboardState.ts(337,64): error TS2322: Type '(event: CardEvent) => void' is not assignable to type '(event: { type: string; payload: Record<string, unknown>; }) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type '{ type: string; payload: Record<string, unknown>; }' is not assignable to type 'CardEvent'.
      Type '{ type: string; payload: Record<string, unknown>; }' is not assignable to type '{ type: "deploy:result"; payload: DeployResultPayload; }'.
        Types of property 'type' are incompatible.
          Type 'string' is not assignable to type '"deploy:result"'.
src/components/dashboard/dashboardState.actions.ts(11,42): error TS6133: 'emitCardDragged' is declared but its value is never read.
src/components/dashboard/dashboardState.actions.ts(74,3): error TS6133: 'storageKey' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/drilldown/views/cluster-drilldown/__tests__/derivedData.test.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30334910161) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21678: 🐛 Build broken after merging PR #21663
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21663.

| Detail | Value |
|--------|-------|
| **PR** | [#21663 — [scanner] fix: split highest-hook-count mission chat components](https://github.com/kubestellar/console/pull/21663) |
| **Author** | @clubanderson |
| **Merge commit** | `f00eea22b7f802d05ea2a0420b31985ea26df1a1` |
| **Detected at** | 2026-07-28 06:36 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> tsc -b && vite build

src/components/dashboard/DashboardState.ts(303,102): error TS2345: Argument of type '{ moveCardToDashboard: (cardId: string, targetDashboardId: string) => Promise<unknown>; createDashboard: (name: string, isDefault?: boolean) => Promise<Dashboard>; ... 4 more ...; t: TFunction<...>; }' is not assignable to parameter of type 'MoveToDashboardDeps'.
  The types returned by 'moveCardToDashboard(...)' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
      Type 'unknown' is not assignable to type 'void'.
src/components/dashboard/DashboardState.ts(309,63): error TS2345: Argument of type '{ moveCardToDashboard: (cardId: string, targetDashboardId: string) => Promise<unknown>; createDashboard: (name: string, isDefault?: boolean) => Promise<Dashboard>; ... 4 more ...; t: TFunction<...>; }' is not assignable to parameter of type 'MoveToDashboardDeps'.
  The types returned by 'moveCardToDashboard(...)' are incompatible between these types.
    Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
      Type 'unknown' is not assignable to type 'void'.
src/components/dashboard/DashboardState.ts(337,64): error TS2322: Type '(event: CardEvent) => void' is not assignable to type '(event: { type: string; payload: Record<string, unknown>; }) => void'.
  Types of parameters 'event' and 'event' are incompatible.
    Type '{ type: string; payload: Record<string, unknown>; }' is not assignable to type 'CardEvent'.
      Type '{ type: string; payload: Record<string, unknown>; }' is not assignable to type '{ type: "deploy:result"; payload: DeployResultPayload; }'.
        Types of property 'type' are incompatible.
          Type 'string' is not assignable to type '"deploy:result"'.
src/components/dashboard/dashboardState.actions.ts(11,42): error TS6133: 'emitCardDragged' is declared but its value is never read.
src/components/dashboard/dashboardState.actions.ts(74,3): error TS6133: 'storageKey' is declared but its value is never read.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/layout/mission-sidebar/mission-chat/MissionChatView.tsx
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatComposer.ts
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatDerived.ts
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatFeedback.ts
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatLifecycle.ts
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatMissionEditor.ts
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatScroll.ts
web/src/components/layout/mission-sidebar/mission-chat/hooks/useMissionChatTitle.ts
web/src/components/layout/mission-sidebar/mission-chat/missionChatConstants.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30334948447) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21675
Fixes #21676
Fixes #21678

## Summary
Minimal TypeScript fixes to restore the main build after run #30334948511 failed with the following compile errors:

- `DashboardState.ts(303,102)` / `(309,63)`: `moveCardToDashboardAction`/`moveCardToNewDashboardAction` expected `moveCardToDashboard` to return `Promise<void>`, but `useDashboards.ts` returned the API response data. Removed the unused return value so the hook matches the `Promise<void>` contract.
- `DashboardState.ts(337,64)`: `ConfirmDeployDeps.publishCardEvent` was typed with a generic `{ type: string; payload: Record<string, unknown> }` shape instead of the actual `CardEvent` union, causing a type mismatch against `useCardPublish()`. Updated the type to use `CardEvent` from `lib/cardEvents`.
- `dashboardState.actions.ts(11,42)`: Removed unused `emitCardDragged` import (still imported/used directly in `DashboardState.ts`).
- `dashboardState.actions.ts(74,3)`: Prefixed unused `storageKey` parameter with `_` in `loadDashboardData` to satisfy `noUnusedParameters`.

No behavioral changes intended; changes are purely typing/import fixes.

### CODE REVIEW

**Comment by clubanderson** [comment]
## CI Diagnosis & Fix Applied — Action Required

### What was failing (`build-gate`)

The `build-gate` job failed with **14 new ESLint violations** in `web/src/components/dashboard/DashboardState.ts` — a file the PR didn't directly change:

- **7× `react-hooks/exhaustive-deps`** — `cardMutationBase` was a plain object literal (line 408), recreated on every render, making all downstream `useCallback` hooks unstable.
- **7× unused `eslint-disable-line` directives** — those disable comments at the `useCallback` dep arrays were written to suppress "missing dep" warnings. Because the violation shifted to line 408 (the object definition), the comments were no longer co-located with any ESLint error, so ESLint reported them as unused.

### Fix applied (commit `1185e75`)

Wrapped `cardMutationBase` in `useMemo` so the object reference is stable across renders:

```ts
// Before
const cardMutationBase = { localCards, dashboard, snapshot, ... }

// After
const cardMutationBase = useMemo(
  () => ({ localCards, dashboard, snapshot, ... }),
  [localCards, dashboard, snapshot, ...]
)
```

The existing `// eslint-disable-line react-hooks/exhaustive-deps` comments on the `useCallback` dep arrays remain valid — they still suppress the legitimate "missing dep" warnings (e.g. `recordCardAdded` used directly from outer scope).

### Two issues still need human action

1. **DCO sign-off missing** — commit `1185e75` was pushed via the GitHub API and lacks a `Signed-off-by:` trailer. You'll need to either:
   - Amend & force-push: `git commit --amend -s` on that commit, or
   - Push a follow-up empty signed commit: `git commit --allow-empty -s -m "chore: add DCO sign-off"`

2. **Branch needs rebase** (`needs-rebase` label) — `main` has moved forward. A `git rebase origin/main` + force-push will clear this and trigger a fresh CI run.

Once rebased with DCO sign-off, the `build-gate` should pass. `Build Frontend` was already ✅.

**Comment by clubanderson** [comment]
Closing as superseded. The current `main` branch already contains all the TypeScript fixes this PR intended to apply — and goes further by properly wrapping `cardMutationBase` in `useMemo` (which resolves the ESLint `react-hooks/exhaustive-deps` violations that were causing the build-gate to fail on this PR).

**What main already has (verified by code inspection):**
- `useDashboards.ts`: `moveCardToDashboard` returns `Promise<void>` ✓  
- `dashboardState.actions.ts`: `MoveToDashboardDeps.moveCardToDashboard` typed as `Promise<void>` ✓  
- `dashboardState.actions.ts`: `emitCardDragged` removed from imports ✓  
- `dashboardState.actions.ts`: `storageKey` param removed from `loadDashboardData` ✓  
- `dashboardState.actions.ts`: `publishCardEvent: (event: CardEvent) => void` ✓  
- `DashboardState.ts`: `cardMutationBase` wrapped in `useMemo` (prevents exhaustive-deps violations) ✓  

**Why this PR would break main if merged:** The PR branch still passes `DASHBOARD_STORAGE_KEY` as a 3rd arg to `loadDashboardData`, but main's signature only accepts 2 params — merging would re-introduce a TypeScript error.
