### ISSUE TITLE
🐛 Frontend build broken: missing Loader2 import in QuantumControlPanel.tsx (regression from PR #18200)

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/console#18221]
## What broke

Frontend build fails on `main` (`6c4b0255f19d`) with:

```
src/components/cards/quantum/QuantumControlPanel.tsx:695:54 -
  error TS2304: Cannot find name 'Loader2'.

695   {(control.executing || isExecuting) ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
                                              ~~~~~~~

Found 1 error.
```

## Root cause

PR #18200 ([scanner] add loading states to async action buttons) added a `<Loader2 />` spinner at `web/src/components/cards/quantum/QuantumControlPanel.tsx:695` but did not include `Loader2` in the existing `lucide-react` destructured import on line 2.

Existing import (line 2):
```ts
import { AlertCircle, Play, Zap, Key, Check, Trash2, ShieldCheck, RefreshCw } from 'lucide-react'
```

Other files modified by PR #18200 may have the same pattern — worth a sweep.

## Reproduction

```bash
git checkout 6c4b0255f
./startup-oauth.sh
# Frontend build fails with TS2304
```

## Fix

PR #18220 — adds `Loader2` to the existing `lucide-react` import. One-line.

cc @kubestellar-hive — please scan the rest of PR #18200's changed files (`grep -l 'Loader2' web/src/components/cards/`) for the same missing-import pattern.

**Comment by KPRoche** [comment]
Duplicate of #18211, which was filed earlier (21:55Z vs 23:37Z). Scanner PR #18215 is already open against that issue with a more complete fix (wires `isExecuting` into the spinner instead of just adding the import).

Closing as duplicate; tracking via #18211.
