### PR TITLE
🐛 fix: resolve TS compiler crash on main

### LINKED ISSUE #21967: 🐛 Build broken after merging PR #21959
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21959.

| Detail | Value |
|--------|-------|
| **PR** | [#21959 — [scanner] fix: split NetworkGlobe and address auto-qa quality issues](https://github.com/kubestellar/console/pull/21959) |
| **Author** | @clubanderson |
| **Merge commit** | `9c7aa6936b8cb3e43f1be121b66d336e18905447` |
| **Detected at** | 2026-07-30 05:24 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

src/components/drilldown/views/helm-release-drilldown/HelmOverviewPanel.tsx(121,20): error TS2345: Argument of type '["common.moreItems", { count: number; }]' is not assignable to parameter of type '[key: "layout.watchdogStageWatchdog" | "layout.watchdogStageNpmInstall" | "layout.watchdogStageParallelBuild" | "layout.watchdogStageFrontendBuild" | "layout.watchdogStageViteStarting" | ... 4834 more ... | ("layout.watchdogStageWatchdog" | ... 4837 more ... | "whiteLabel.copyCommands")[], options?: { ...; } | undef...'.
  Type '["common.moreItems", { count: number; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: ({ readonly count: number; } & $Dictionary) | undefined]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ count: number; }' is not assignable to type 'string'.
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/animations/globe/NetworkGlobe.geometry.ts
web/src/components/animations/globe/NetworkGlobe.tsx
web/src/components/dashboard/customDashboard/DashboardEmptyState.tsx
web/src/components/drilldown/views/helm-release-drilldown/HelmOverviewPanel.tsx
web/src/components/drilldown/views/multi-cluster-summary-drilldown/ClusterSummaryCard.tsx
web/src/locales/en/common.json
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30516246378) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### LINKED ISSUE #21976: 🐛 Build broken after merging PR #21960
## Build Broken After Merge

The post-merge build verification detected a **build failure** after merging PR #21960.

| Detail | Value |
|--------|-------|
| **PR** | [#21960 — 🌱 refactor: split oversized drilldown components](https://github.com/kubestellar/console/pull/21960) |
| **Author** | @clubanderson |
| **Merge commit** | `960a6fc5aa1ea9dfe6c9a18d55f5d1ac44774bf7` |
| **Detected at** | 2026-07-30 05:46 UTC |

### Frontend Build Failure
```

> kubestellar-console@0.1.0 build
> NODE_OPTIONS=--max-old-space-size=6144 tsc -b && NODE_OPTIONS=--max-old-space-size=6144 vite build

/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:123693
      throw e;
      ^

Error: Debug Failure. No error for last overload signature
    at resolveCall (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:76665:19)
    at resolveCallExpression (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77047:12)
    at resolveSignature (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77475:16)
    at getResolvedSignature (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77502:20)
    at checkCallExpression (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:77610:23)
    at checkExpressionWorker (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:81068:16)
    at checkExpression (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:80966:32)
    at checkExpressionCached (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:80590:28)
    at checkVariableLikeDeclaration (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:83508:35)
    at checkVariableDeclaration (/home/runner/work/console/console/web/node_modules/typescript/lib/_tsc.js:83604:5)

Node.js v22.23.1
```

## Files Changed in PR

<details>
<summary>Click to expand file list</summary>

```
web/src/components/drilldown/views/EventsDrillDown.parts.tsx
web/src/components/drilldown/views/EventsDrillDown.tsx
web/src/components/drilldown/views/NamespaceDrillDown.parts.tsx
web/src/components/drilldown/views/NamespaceDrillDown.tsx
web/src/components/drilldown/views/PVCDrillDown.parts.tsx
web/src/components/drilldown/views/PVCDrillDown.tsx
web/src/components/drilldown/views/PolicyDrillDown.parts.tsx
web/src/components/drilldown/views/PolicyDrillDown.tsx
web/src/components/drilldown/views/ReplicaSetDrillDown.parts.tsx
web/src/components/drilldown/views/ReplicaSetDrillDown.tsx
web/src/components/drilldown/views/useEventsDrillDown.ts
web/src/components/drilldown/views/useNamespaceDrillDown.ts
web/src/components/drilldown/views/usePVCDrillDown.ts
web/src/components/drilldown/views/usePolicyDrillDown.ts
web/src/components/drilldown/views/useReplicaSetDrillDown.ts
```

</details>

## Next Steps

1. Check the [workflow run](https://github.com/kubestellar/console/actions/runs/30517275575) for full logs
2. Identify the breaking change from the files listed above
3. Submit a fix PR or revert the merge commit

---
*This issue was automatically created by the post-merge build verification workflow.*

### PR DESCRIPTION
**Pull request by clubanderson**
Fixes #21967
Fixes #21976

## Root cause

`main` is broken: `npm run build` (`tsc -b`) crashes with an internal TypeScript compiler assertion failure (not a normal type error):

```
Error: Debug Failure. No error for last overload signature
    at resolveCall (.../_tsc.js:76665:19)
    at resolveCallExpression
    at resolveSignature
    at getResolvedSignature
    at checkCallExpression
    ...
```

This is a known upstream TypeScript bug ([microsoft/TypeScript#63195](https://github.com/microsoft/TypeScript/issues/63195)): react-i18next's heavily-overloaded `t()` function is type-checked against a `CustomTypeOptions.resources` type derived via `typeof` directly from our translation JSON. `web/src/locales/en/common.json` + `en/cards.json` have grown to ~10,000 lines combined, crossing the threshold that trips this TS overload-resolution bug. It tipped over on the commit that merged #21960 (`960a6fc5aa`), which added more `t()` call sites in the newly split drilldown components (e.g. `EventsDrillDown.parts.tsx`).

## Fix

`web/src/lib/i18n.ts` keeps full type-safety for translation **keys** (used by `t()` autocompletion / dot-path validation), but now widens every leaf **value** type to `string` via a recursive mapped type (`FlattenLeafValues`), instead of using the literal JSON value types directly. This avoids the combinatorial overload blow-up that was crashing `tsc -b`, with no change to any runtime behavior or translation content.

```ts
type FlattenLeafValues<T> = {
  [K in keyof T]: T[K] extends object ? FlattenLeafValues<T[K]> : string
}

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS
    resources: FlattenLeafValues<typeof resources['en']>
  }
}
```

## Files changed

- `web/src/lib/i18n.ts`

## Note on related PRs

This is the same systemic fix proposed independently in #21998 (which targets the identical root cause with an identical diff) — that PR remains open/blocked. #21993 takes a narrower approach of relocating specific offending `t()` call sites to existing valid keys, which only patches the two call sites it identified rather than the general overload-resolution trigger. This PR should unblock `main` regardless of which of those two also lands; if #21998 merges first, this PR becomes a no-op duplicate and can be closed.

Per repo guidelines, `npm run build` / `npm run lint` were **not** run locally — CI validates both on the PR.

### CODE REVIEW

**Comment by clubanderson** [comment]
FYI: verified via this PR's own CI logs that this diff (identical to #21998) still hits the exact same `tsc -b` crash (`Debug Failure. No error for last overload signature`) — see the `Build Frontend` job at https://github.com/kubestellar/console/actions/runs/30526785381/job/90819458401, which ran after this PR's latest push. Widening only the leaf *values* to `string` isn't sufficient; the crash is driven by the size of the derived *key* union, not the value types.

Opened #22015 which removes the `typeof`-derived resources typing entirely and is verified green on `Build Frontend` / multi-arch `build` / `fullstack-smoke`. Linking here for visibility — not asking you to close this, just flagging so we don't land two competing fixes.

**Comment by clubanderson** [comment]
Pushed a fixup commit (`59d700c776`) merging latest `main` into this branch. `main` already merged #22014 with the definitive fix (removing the `CustomTypeOptions.resources` typing entirely from `web/src/lib/i18n.ts`), which supersedes this PR's `FlattenLeafValues` approach. Resolved the `i18n.ts` conflict by keeping `main`'s version, since it's the one confirmed to stop the `tsc -b` crash in CI. This PR's diff is now effectively a no-op vs. `main` on that file; leaving open per instructions not to close PRs.
